"""IDE-side Agent Bridge service launcher (IDE_NAME_TBD, slice 2).

Starts the canonical Agent Bridge runtime via its supported CLI
(``cli.py serve`` -> HTTP /v1 on 127.0.0.1) as a child process and
waits until ``/health`` responds. The Agent Bridge repository itself
is never modified: it is only executed.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

from .bridge_config import BridgeConfig


def _injected_launcher(cfg: BridgeConfig, external_approvals: bool,
                       approval: str, script: list[str]) -> str:
    """Source of the child-process launcher used by start_injected().

    Written to the worker directory (git-ignored) and executed with the Agent
    Bridge checkout as cwd. It imports the Bridge's own modules unmodified and
    serves them; the only caller-supplied value is the scripted model.
    """
    return f'''"""IDE vertical-slice launcher: real Bridge service, injected model.

Generated by IDE-Workspace workspace/integration/bridge_service.py.
Not part of the Agent Bridge repository.
"""
import json
import sys

sys.path.insert(0, {cfg.agent_bridge_root!r})

from runtime import AgentRuntime, RuntimeConfig
from service import serve

SCRIPT = json.loads({json.dumps(json.dumps(script))})
APPROVAL = {approval or cfg.approval!r}
EXTERNAL = {bool(external_approvals)!r}


class _ScriptedProvider:
    """One scripted model. Not a mock of the runtime: the runtime, the approval
    gate, the policy engine and the executor all run for real."""

    def __init__(self, script, model="ide-vertical-slice-model"):
        self._script = list(script)
        self.model = model

    def list_models(self):
        return [self.model]

    def chat(self, messages, temperature=0.1, num_predict=640):
        if self._script:
            return self._script.pop(0)
        return '{{"action":"finish","message":"vertical slice complete"}}'


def _factory(role):
    return _ScriptedProvider(SCRIPT)


def main() -> int:
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8471
    rt = AgentRuntime(
        RuntimeConfig(
            allowed_workspace_roots=[{cfg.workspace_root!r}],
            default_approval=APPROVAL,
            external_approvals=EXTERNAL,
        ),
        provider_factory=_factory,
    )
    srv = serve(rt, "127.0.0.1", port)
    print(f"injected bridge serving /v1 on http://127.0.0.1:{{port}}", flush=True)
    srv.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


class BridgeService:
    def __init__(self, config: BridgeConfig | None = None):
        self.config = config or BridgeConfig()
        self.proc: subprocess.Popen | None = None

    def start(
        self,
        approval: str = "",
        preset: str = "STANDARD",
        port: int = 0,
        timeout_s: float = 90,
        external_approvals: bool | None = None,
    ) -> str:
        cfg = self.config
        root = cfg.agent_bridge_root
        if not root:
            raise RuntimeError("AGENT_BRIDGE_ROOT is not configured")
        external = cfg.external_approvals if external_approvals is None else external_approvals
        endpoint = cfg.endpoint
        if port:
            endpoint = f"http://127.0.0.1:{port}"
        host_port = endpoint.rsplit("://", 1)[-1]
        host, _, port_s = host_port.partition(":")
        cmd = [
            sys.executable,
            str(Path(root) / "cli.py"),
            "--root", cfg.workspace_root,
            "--approval", approval or cfg.approval,
            "--preset", preset,
        ]
        if external:
            # Owner switch for a human-in-the-loop runtime. Without it the
            # runtime denies anything that needs an ask instead of asking, and
            # a session asking for interactivity is refused with 403.
            cmd.append("--external-approvals")
        cmd += [
            "serve",
            "--host", host or "127.0.0.1",
            "--port", str(int(port_s or 8471)),
        ]
        log_path = Path(cfg.workspace_root) / ".agent-worker-test" / "bridge-service.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        logf = open(log_path, "ab")
        self.proc = subprocess.Popen(
            cmd, cwd=root, stdout=logf, stderr=subprocess.STDOUT
        )
        logf.close()
        deadline = time.time() + timeout_s
        last_err = ""
        health_url = endpoint.rstrip("/") + "/health"
        while time.time() < deadline:
            if self.proc.poll() is not None:
                raise RuntimeError(f"bridge service exited early (rc={self.proc.returncode})")
            try:
                with urllib.request.urlopen(health_url, timeout=5) as resp:
                    if resp.status == 200:
                        return endpoint
            except Exception as e:  # not up yet
                last_err = str(e)[:200]
            time.sleep(1.0)
        self.stop()
        raise TimeoutError(f"bridge /health never responded: {last_err}")

    def stop(self) -> None:
        if self.proc is not None and self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                self.proc.kill()
        self.proc = None

    def start_injected(
        self,
        script: list[str],
        port: int = 0,
        timeout_s: float = 60,
        external_approvals: bool = True,
        approval: str = "",
    ) -> str:
        """Start the real Bridge HTTP service with a scripted model.

        What is real here: the Bridge service, the runtime, session and task
        lifecycle, the approval gate, the policy engine, the executor and the
        sandbox. The single injected part is the model, scripted by the caller.
        This exists so the vertical slice can be proven deterministically:
        model behaviour and architecture correctness are separate questions, and
        a bad model answer must not be able to fail - or fake - a
        transport/authority test.

        It launches a child process running a generated launcher from the Agent
        Bridge checkout. The Agent Bridge repository is not modified.
        """
        cfg = self.config
        root = cfg.agent_bridge_root
        if not root:
            raise RuntimeError("AGENT_BRIDGE_ROOT is not configured")
        if not script:
            raise ValueError("script must contain at least one model response")
        source = _injected_launcher(cfg, external_approvals, approval, list(script))
        launcher = Path(cfg.worker_dir) / "injected_service_launcher.py"
        launcher.parent.mkdir(parents=True, exist_ok=True)
        launcher.write_text(source, encoding="utf-8")
        log_path = launcher.parent / "injected-service.log"
        logf = open(log_path, "ab")
        try:
            self.proc = subprocess.Popen(
                [sys.executable, str(launcher), str(port)],
                cwd=root, stdout=logf, stderr=subprocess.STDOUT,
            )
        finally:
            logf.close()
        endpoint = f"http://127.0.0.1:{port}"
        deadline = time.time() + timeout_s
        health_url = endpoint + "/health"
        last_err = ""
        while time.time() < deadline:
            if self.proc.poll() is not None:
                tail = ""
                try:
                    tail = log_path.read_text(encoding="utf-8", errors="replace")[-800:]
                except OSError:
                    pass
                raise RuntimeError(
                    f"injected bridge service exited early "
                    f"(rc={self.proc.returncode}): {tail}")
            try:
                with urllib.request.urlopen(health_url, timeout=5) as resp:
                    if resp.status == 200:
                        return endpoint
            except Exception as e:  # not up yet
                last_err = str(e)[:200]
            time.sleep(0.5)
        self.stop()
        raise TimeoutError(f"injected bridge /health never responded: {last_err}")
